[Icon Theme]
Name=TemaDefinitivo
Comment=Tema personalizado
Inherits=Papirus-Dark,Papirus,hicolor
#Inherits=Adwaitaru,Papirus,breeze-dark,hicolor

FollowsColorScheme=true

Directories=places/scalable,places/symbolic,apps/scalable

[places/symbolic]
Context=Places
Size=16
MinSize=8
MaxSize=22
Type=Fixed

[places/scalable]
Context=Places
Size=128
MinSize=32
MaxSize=512
Type=Scalable

[apps/scalable]
Context=Places
Size=128
MinSize=32
MaxSize=512
Type=Scalable

